Connectio/ViewModels/CreateCommentViewModel.cs
using Connectio.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace Connectio.ViewModels
{
    /// <summary>
    /// CreateComment represent model for creating new comment.
    /// </summary>
    public class CreateCommentViewModel
    {        
        /// <summary>
        /// Body text content of comment.
        /// </summary>
        [Required]
        [StringLength(256, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 1)]
        public string Text { get; set; } = string.Empty;
    }
}

Connectio/Controllers/ReactionController.cs
using Connectio.Data;
using Connectio.Models;
using Connectio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Connectio.Controllers
{
    /// <summary>
    /// Reaction controller manages reactions on posts.
    /// </summary>
    [Authorize]
    public class ReactionController : Controller
    {
        private readonly IReactionRepository _reactionRepository;
        private readonly IPostRepository _postRepository;
        private readonly IMentionRepository _mentionRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReactionController(IReactionRepository reactionRepository, IPostRepository postRepository, IMentionRepository mentionRepository, UserManager<ApplicationUser> userManager)
        {
            _reactionRepository = reactionRepository;
            _postRepository = postRepository;
            _mentionRepository = mentionRepository;
            _userManager = userManager;
        }

        /// <summary>
        /// Displays all likes on post.
        /// </summary>
        /// <param name="postId">Post id to view likes.</param>
        /// <returns>View containing all users, who liked the post.</returns>
        public IActionResult DisplayPostLikes(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            if(post == null)
            {
                return NotFound();
            }

            var likedBy = new ReadPostLikesViewModel(post.LikedBy, post);
            
            return View(likedBy);
        }

        /// <summary>
        /// Displays logged in user bookmarks.
        /// </summary>
        /// <returns>View with list of all posts bookmarked by logged in user.</returns>
        public async Task<IActionResult> UserBookmarks()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }

            var bookmarks = _reactionRepository.GetAllBookmarks(user);

            return View(new ReadAllBookmarksViewModel(bookmarks));
        }

        /// <summary>
        /// Add post to user bookmarks.
        /// </summary>
        /// <param name="postId">Post id to be bookmarked.</param>
        /// <returns>View with all users' bookmarks.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBookmark(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            var user = await _userManager.GetUserAsync(User);
            if (user == null || post == null)
            {
                return NotFound();
            }

            var bookmark = new Bookmark()
            {
                User = user,
                Post = post
            };
            _reactionRepository.CreateBookmark(bookmark);
            return RedirectToAction("UserBookmarks");
        }

        /// <summary>
        /// Remove post from user bookmarks.
        /// </summary>
        /// <param name="postId">Post id to be removed from bookmarks.</param>
        /// <returns>View with all users' bookmarks.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteBookmark(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            var user = await _userManager.GetUserAsync(User);
            if (user == null || post == null)
            {
                return NotFound();
            }

            var bookmark = _reactionRepository.GetBookmark(user, post);
            if(bookmark == null)
            {
                return NotFound();
            }

            _reactionRepository.DeleteBookmark(bookmark);
            return RedirectToAction("UserBookmarks");
        }

        /// <summary>
        /// Like a post.
        /// </summary>
        /// <param name="postId">Post to be liked.</param>
        /// <returns>Returns to home screen.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLike(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            var user = await _userManager.GetUserAsync(User);
            if (user == null || post == null)
            {
                return NotFound();
            }

            var like = new Like()
            {
                User = user,
                Post = post
            };
            _reactionRepository.CreateLike(like);
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Remove like from post.
        /// </summary>
        /// <param name="postId">Post from which like should be removed.</param>
        /// <returns>Returns to home screen.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLike(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            var user = await _userManager.GetUserAsync(User);
            if (user == null || post == null)
            {
                return NotFound();
            }

            var like = _reactionRepository.GetLike(user, post);
            if (like == null)
            {
                return NotFound();
            }

            _reactionRepository.DeleteLike(like);
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Displays form for writing new comment.
        /// </summary>
        /// <param name="postId">Post id to be commented.</param>
        /// <returns>View with form for writing new comment.</returns>
        public IActionResult CreateComment(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            if(post == null)
            {
                return NotFound();
            }

            return View(new DisplayCreateCommentViewModel(post));
        }

        /// <summary>
        /// Creates new comment on a post.
        /// </summary>
        /// <param name="postId">Post id to be commented.</param>
        /// <param name="newComment">ViewModel for comment to be added.</param>
        /// <returns>View displaying post with newly added comment.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment(int postId, CreateCommentViewModel newComment)
        {

            var post = _postRepository.GetPostById(postId);
            var user = await _userManager.GetUserAsync(User);
            if (user == null || post == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(new DisplayCreateCommentViewModel(post, newComment.Text));
            }
            
            var comment = new Comment()
            {
                User = user,
                Post = post,
                Text = newComment.Text
            };
            _reactionRepository.CreateComment(comment);
            return RedirectToAction("Index", "Post", new { id = postId });
        }

        /// <summary>
        /// Displays all posts with given tag.
        /// </summary>
        /// <param name="tagName">Tag to be viewed.</param>
        /// <returns>View containing all posts with given tag.</returns>
        [AllowAnonymous]
        public IActionResult PostsWithTag(string tagName)
        {
            var tag = _mentionRepository.GetTag(tagName);
            if (tag == null)
            {
                return NotFound();
            }

            var posts = _mentionRepository.GetPosts(tag);

            var tagViewModel = new ReadTagViewModel(tag);
            var postsViewModel = posts.Select(p => new ReadPostViewModel(p));
            
            var viewModel = new ReadPostsWithTagViewModel(tagViewModel, postsViewModel);
            return View(viewModel);
        }
    }
}

Connectio/Views/Reaction/CreateComment.cshtml
@model DisplayCreateCommentViewModel

@{
    ViewData["Title"] = "New comment";
}

<partial name="_PostCard" model="@Model.Post" />

<div id="new_comment" class="w-full mb-4 rounded-xl bg-white p-5 shadow scroll-mt-16">
    <span asp-validation-for="@Model.Text" class="text-red-500"></span>
    <div class="flex justify-between">
        <div class="w-full my-auto">
            <form asp-controller="Reaction" asp-action="CreateComment" asp-route-postId="@Model.Post.Id">
                <input asp-for="@Model.Text" class="w-full p-3 mb-2 focus:outline-0" type="text" placeholder="What is your reply?">
                <div class="flex justify-between pl-3">
                    <div>
                        <button id="new-comment-submit" type="submit" class="rounded-full bg-orange-400 px-3 py-2 w-32 font-semibold text-white hover:bg-orange-500">Post</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Connectio/Views/Reaction/DisplayPostLikes.cshtml
@model ReadPostLikesViewModel

<partial name="_PostCard" model="@Model.Post" />

<partial name="_Divider" model=@("Post likes (" + Model.LikedBy.Count() + ")") />

@foreach(var user in Model.LikedBy){
    <div class="w-full mb-4 rounded-xl bg-white px-5 py-1 shadow">
        <div class="w-full rounded-lg my-4">
            <div class="w-full flex">
                <div class="mr-3">
                    <partial name="User/_SmallProfilePicture" model="user" />
                </div>
                <div>
                    <a asp-controller="User" asp-action="Index" asp-route-username="@user.UserName" class="hover:underline">
                        <div class="flex items-center">
                        <span class="font-semibold">@user.DisplayName</span>
                        @if (user.Verified)
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 ml-1">
                                <path fill-rule="evenodd" d="M8.603 3.799A4.49 4.49 0 0112 2.25c1.357 0 2.573.6 3.397 1.549a4.49 4.49 0 013.498 1.307 4.491 4.491 0 011.307 3.497A4.49 4.49 0 0121.75 12a4.49 4.49 0 01-1.549 3.397 4.491 4.491 0 01-1.307 3.497 4.491 4.491 0 01-3.497 1.307A4.49 4.49 0 0112 21.75a4.49 4.49 0 01-3.397-1.549 4.49 4.49 0 01-3.498-1.306 4.491 4.491 0 01-1.307-3.498A4.49 4.49 0 012.25 12c0-1.357.6-2.573 1.549-3.397a4.49 4.49 0 011.307-3.497 4.49 4.49 0 013.497-1.307zm7.007 6.387a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z" clip-rule="evenodd" />
                            </svg>
                        }
                    </div>
                </a>
                <div class="text-sm text-gray-600"><span>@@@user.UserName</span></div>
                </div>
            </div>
        </div>
    </div>
}

Connectio/Views/Reaction/PostsWithTag.cshtml
@model ReadPostsWithTagViewModel

@{
    ViewData["Title"] = $"Posts tagged with {Model.Tag.Name} / Connectio";
}

@if(Model.Posts.Count() == 0)
{
    <div class="text-center">
        <h3 class="font-semibold text-lg text-gray-800">No posts found</h3>
    </div>
}
else
{
    <partial name="_Divider" model=@("Posts with tag&nbsp<strong>#" + Model.Tag.Name+"</strong>") />
    foreach(var post in Model.Posts)
    {
        <partial name="_PostCard" model="post" />
    }
}

Connectio/Views/Reaction/UserBookmarks.cshtml
@model ReadAllBookmarksViewModel

@{
    ViewData["Title"] = "Bookmarks";
    ViewData["ActiveNavigationPage"] = ActiveNavigationPage.Bookmarks;
}

@if(Model.BookmarkedPosts.Count() == 0)
{
    <partial name="_Divider" model="@("You haven't bookmarked any posts")" />
}

@foreach (var bookmark in Model.BookmarkedPosts)
{
    <partial name="_PostCard" model="bookmark" />
}